#!/bin/bash

cd "$(dirname "${BASH_SOURCE[0]}")" || exit 1

source _common/convert.bash

parallel find '{}' '>/dev/null' '2>/dev/null' '&&' svg2png '{}' ::: *.svg
parallel find '{}' '>/dev/null' '2>/dev/null' '&&' render_blender '{}' ::: *.rendernormal.blend
parallel find '{}' '>/dev/null' '2>/dev/null' '&&' render_blender_marker '{}' ::: *.rendermarker.blend

list_rendered() {
	printf "["
	for i in *.png; do
		printf \"
		printf "%s" "$i" # SC2059. filenames could contain '%' which would be parsed
		printf \"
		printf ","
	done
	printf "\"skin.ini\""
	printf ']\n' # single quote so \n is parsed by printf not bash
}

list_rendered >to-move
